### PR TITLE
Use flush_input to flush the input buffer.

### PR DESCRIPTION
**Pull request by kimhmadsen**
This fix avoids calling readpartial on Windows platform which is very slow. Plus the code becomes a little cleaner.

### CODE REVIEW

**Comment by flipback** [comment]
Great!. So much code and bugs around the flushing, while the obvious solution was so near.  Tanks a lot for the patch!

**Comment by cygnus6** [comment]
Hi,

This commit seems to break ModBus::RTUViaTCPClient for me.
i'm using ruby v2.2.2 with rails 4.2.1 running on thin server.
I get this stack trace when i try to read a holding register:
```
/usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/rtu.rb:50:in `clean_input_buff': undefined method `flush_input' for #<TCPSocket:fd 9> (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/rtu.rb:71:in `send_rtu_pdu'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/rtu_via_tcp_slave.rb:33:in `send_pdu'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/slave.rb:247:in `block in query'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:125:in `timeout'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/slave.rb:246:in `query'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/slave.rb:177:in `read_holding_registers'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/proxy.rb:26:in `[]'
	from /var/rails_apps/iothub/code/iothub-nibe/app/models/nibe.rb:160:in `block in read_registers'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/rmodbus-1.2.6/lib/rmodbus/client.rb:69:in `with_slave'
	from /var/rails_apps/iothub/code/iothub-nibe/app/models/nibe.rb:157:in `read_registers'
	from /var/rails_apps/iothub/code/iothub-nibe/app/models/nibe.rb:87:in `update_holding_registers'
	from /var/rails_apps/iothub/code/iothub-nibe/app/models/nibe.rb:56:in `block in refresh'
	from /var/rails_apps/iothub/code/iothub-nibe/app/models/nibe.rb:55:in `synchronize'
	from /var/rails_apps/iothub/code/iothub-nibe/app/models/nibe.rb:55:in `refresh'
	from /var/rails_apps/iothub/code/iothub-nibe/config/application.rb:33:in `block (2 levels) in <class:Application>'
```
The application works when i revert this commit.
additionally, i don't know if this is related or just a configuration issue, but i'm not confident all data is returned correctly.
```
Tx (8 bytes): [01][03][0c][08][00][01][06][98]
Rx (7 bytes): [01][03][02][00][0e][39][80]
```
i never get more than 7 bytes, while sometimes 8 bits of data and other times 32 bits should be returned.

Please let me know if i'm just not using this right or some things actually need to be fixed.

**Comment by flipback** [comment]
Thanks for the report! I have made a little patch. Try it please and say if everything is ok. I would very grateful if you check it for RTUClient too because I haven't got any equipment to do it on my own.

**Comment by cygnus6** [comment]
this works, thanks!
Unfortunately i also don't have the possibility to test the device directly to see if RTUClient works.

**Pull request merged**
